version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: tuum-postgres
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tuum-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
